FROM selenium/standalone-chrome-debug
#nkovacs/selenium-standalone-phantomjs
# selenium/standalone-chrome

LABEL maintainer="Khary Sharpe <ksharpe@email.com>"

RUN x11vnc -storepasswd password /home/seluser/.vnc/passwd
